<#
.SYNOPSIS
    Scan session files for decision markers and rebuild INDEX.md
.PARAMETER Project
    Path to the target project containing TRAIL/
.PARAMETER DryRun
    Show what would be generated without writing
#>
param(
    [string]$Project = (Get-Location).Path,
    [switch]$DryRun
)

$sessionsDir = Join-Path (Join-Path $Project "TRAIL") "sessions"
$indexPath = Join-Path (Join-Path $Project "TRAIL") "INDEX.md"

if (-not (Test-Path $sessionsDir)) {
    Write-Error "No TRAIL/sessions/ found in $Project"
    exit 1
}

# Scan all session files for [!DECISION] markers
$decisions = @()
$sessionFiles = Get-ChildItem -Path $sessionsDir -Filter "*.md" | Sort-Object Name

foreach ($file in $sessionFiles) {
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    $lines = $content -split "`n"
    
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -match '\[!DECISION\]') {
            # Extract decision text — the rest of the line after the marker
            $decisionText = ($lines[$i] -replace '.*\[!DECISION\]\s*', '').Trim()
            
            # Look for rationale in the next few lines (indented or prefixed with "Rationale:")
            $rationale = ""
            $alternatives = ""
            for ($j = $i + 1; $j -lt [Math]::Min($i + 10, $lines.Count); $j++) {
                if ($lines[$j] -match '^\s*Rationale:\s*(.+)') {
                    $rationale = $Matches[1].Trim()
                }
                if ($lines[$j] -match '^\s*Alternatives:\s*(.+)') {
                    $alternatives = $Matches[1].Trim()
                }
                # Stop at next marker or blank line after content
                if ($lines[$j] -match '^\[!' -or ($lines[$j].Trim() -eq '' -and $j -gt $i + 1)) {
                    break
                }
            }
            
            $decisions += [PSCustomObject]@{
                File = $file.Name
                Slug = $file.BaseName -replace '^\d{4}-\d{2}-\d{2}-', ''
                Date = if ($file.Name -match '^(\d{4}-\d{2}-\d{2})') { $Matches[1] } else { "unknown" }
                Line = $i + 1
                Text = $decisionText
                Rationale = $rationale
                Alternatives = $alternatives
            }
        }
    }
}

Write-Host "Found $($decisions.Count) decisions across $($sessionFiles.Count) session files."

if ($decisions.Count -eq 0) {
    Write-Host "No [!DECISION] markers found. Nothing to index."
    exit 0
}

# Check for existing INDEX.md to preserve manual entries
$existingManual = @()
if (Test-Path $indexPath) {
    $existingContent = [System.IO.File]::ReadAllText($indexPath, [System.Text.Encoding]::UTF8)
    # Extract DEC-R entries (retroactive, manually maintained)
    if ($existingContent -match '(?s)(### DEC-R\d+.+?)(?=### DEC-\d|## |$)') {
        # Preserve all DEC-R entries
        $retroMatches = [regex]::Matches($existingContent, '(?s)(### DEC-R\d+.+?)(?=### DEC-R\d|### DEC-\d|## [^#]|$)')
        foreach ($m in $retroMatches) {
            $existingManual += $m.Value.TrimEnd()
        }
    }
}

# Generate index
$output = @"
# Decision Index

*Auto-generated by kiroku-index.ps1. Retroactive (DEC-R) entries are manually maintained.*
*Last rebuilt: $(Get-Date -Format "yyyy-MM-dd HH:mm")*

---

"@

# Add retroactive entries first
if ($existingManual.Count -gt 0) {
    $output += "`n## Retroactive Decisions (pre-trail)`n`n"
    foreach ($entry in $existingManual) {
        $output += "$entry`n`n"
    }
    $output += "---`n`n"
}

# Add discovered decisions
$output += "## Decisions`n`n"
$num = 1
foreach ($dec in $decisions) {
    $anchor = "L$($dec.Line)"
    $output += @"
### DEC-$('{0:D3}' -f $num): $($dec.Text)
- **Date:** $($dec.Date)
- **Session:** [$($dec.Slug)](sessions/$($dec.File)#$anchor)
- **Fidelity:** reconstructed
- **Decision:** $($dec.Text)
- **Rationale:** $(if ($dec.Rationale) { $dec.Rationale } else { '*not recorded at decision point*' })
- **Alternatives considered:** $(if ($dec.Alternatives) { $dec.Alternatives } else { '*not recorded*' })
- **Status:** active

"@
    $num++
}

if ($DryRun) {
    Write-Host "`n--- DRY RUN OUTPUT ---"
    Write-Host $output
} else {
    [System.IO.File]::WriteAllText($indexPath, $output, [System.Text.Encoding]::UTF8)
    Write-Host "INDEX.md updated with $($decisions.Count) decisions at $indexPath"
}
